name: Release

on:
  push:
    tags:
      'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux_amd64
            artifact: verdandi-linux-amd64

          - os: ubuntu-24.04-arm
            artifact: verdandi-linux-arm64

          - os: windows-latest
            target: windows_amd64
            artifact: verdandi-windows-amd64.exe

          - os: macos-latest
            target: darwin_arm64
            artifact: verdandi-mac-arm64

          - os: macos-13
            target: darwin_amd64
            artifact: verdandi-mac-amd64

      runs-on: ${{ matrix.os }}

      steps:
        - uses: actions/checkout@v4

        - uses: laytan/setup-odin@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            release: latest

        - name: Build
          shell: bash
          run: odin build . -o:speed -out:${{ matrix.artifact }}

        - uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.artifact }}
            path: ${{ matrix.artifact }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: artifacts/

      - uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
